version: '3'
services:
  web:
    image: greg78/node:latest
    ports:
      - "8080:3000"
    volumes:
      - D:\www\local.dev\bank.io\API:/usr/src/app
      - D:\www\local.dev\bank.io\API\package.json:/usr/src/app/package.json
    links:
      - db
    command: npm start
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: